namespace: a8s-system
replicaCount: 1

crd:
  enable: true
  keep: true

image:
  repository: public.ecr.aws/w5n9a2g2/a9s-ds-for-k8s/dev/service-binding-controller
  tag: 39037b5e4148d69dae1cbe35857e3a705eafb5d6
  pullPolicy: IfNotPresent
kubeRbacProxyImage:
  repository: quay.io/brancz/kube-rbac-proxy
  tag: v0.16.0
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
  name: service-binding-manager-account
controllerConfig:
  postgresqlRootRole: a9s_user
  postgresqlDefaultDatabase: a9s_apps_default_db
  leaderElection: true
service:
  port: 8443
  annotations: {}
resources:
  manager:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  kubeRbacProxy:
    limits:
      cpu: 400m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi
nodeSelector: {}
tolerations: []
affinity: {}
