apiVersion: v1
data:
  backupAgentImage: public.ecr.aws/w5n9a2g2/a9s-ds-for-k8s/dev/backup-agent:726a6660fa911e554356d6d3dbe929e5485f79d7
  spiloImage: registry.opensource.zalan.do/acid/spilo-14:2.1-p6
  extensionImageRegistry: public.ecr.aws/w5n9a2g2/a9s-ds-for-k8s/dev/postgresql-operator/postgresql-extensions
  extensionCleanupImage: alpine:3.16.0
kind: ConfigMap
metadata:
  name: postgresql-images
  namespace: a8s-system
