{{- $namespace := include "a8s-postgresql-operator.namespace" . -}}
{{- $saName := default "postgresql-manager-account" .Values.serviceAccount.name -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: postgresql-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: postgresql-operator
    app.kubernetes.io/part-of: a8s-postgres
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: postgresql-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ $namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: postgresql-proxy-rolebinding
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: postgresql-operator
    app.kubernetes.io/part-of: a8s-postgres
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: postgresql-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ $namespace }}
