apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: a8s
    app.kubernetes.io/name: fluentd-aggregator
    app.kubernetes.io/part-of: a8s-logging
  name: a8s-fluentd-aggregator
  namespace: a8s-system
spec:
  ports:
  - name: monitor
    port: 24220
    protocol: TCP
    targetPort: monitor
  - name: forward
    port: 24224
    protocol: TCP
    targetPort: forward
  selector:
    app.kubernetes.io/instance: a8s
    app.kubernetes.io/name: fluentd-aggregator
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: a8s
    app.kubernetes.io/name: fluentd-aggregator
    app.kubernetes.io/part-of: a8s-logging
    a8s.anynines/logging: "true"
  name: a8s-fluentd-aggregator
  namespace: a8s-system
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: a8s
      app.kubernetes.io/name: fluentd-aggregator
      a8s.anynines/logging: "true"
  serviceName: a8s-fluentd-aggregator
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: a8s
        app.kubernetes.io/name: fluentd-aggregator
        a8s.anynines/logging: "true"
    spec:
      containers:
      - image: public.ecr.aws/w5n9a2g2/a9s-ds-for-k8s/dev/fluentd:v1.12.3-1.0-1.0.0
        imagePullPolicy: IfNotPresent
        name: fluentd-aggregator
        ports:
        - containerPort: 9880
          name: http
          protocol: TCP
        - containerPort: 24220
          name: monitor
          protocol: TCP
        - containerPort: 24224
          name: forward
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluentd/etc
          name: config
        - mountPath: /fluentd/buffers
          name: buffer
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        secret:
          defaultMode: 511
          secretName: a8s-fluentd-aggregator
      - emptyDir: {}
        name: buffer
