apiVersion: v1
data:
  fluent.conf: |-
    <source>
      @type forward
      bind 0.0.0.0
      port 24224
    </source>

    <match **>
      @type copy
      <store>
        @type label_router
        <route>
          @label @POSTGRES
          tag postgres_tag
          <match>
            labels cluster-name:sample-pg-cluster
          </match>
        </route>
      </store>
      <store>
        @type elasticsearch
        @id out_es
        include_tag_key true
        host a8s-opendistro-es-client-service.a8s-system.svc.cluster.local
        port 9200
        scheme 'http'
        ssl_verify 'true'
        ssl_version 'TLSv1_2'
        user 'admin'
        password 'admin'
        reload_connections 'false'
        reconnect_on_error 'true'
        reload_on_failure 'true'
        log_es_400_reason 'false'
        logstash_prefix 'logstash'
        logstash_dateformat '%Y.%m.%d'
        logstash_format 'true'
        index_name 'logstash'
        target_index_key use_nil
        type_name 'fluentd'
        include_timestamp 'false'
        request_timeout '5s'
        application_name use_default
        suppress_type_name 'true'
        enable_ilm 'false'
        ilm_policy_id use_default
        ilm_policy use_default
        ilm_policy_overwrite 'false'
        <buffer>
          flush_thread_count '8'
          flush_interval '5s'
          chunk_limit_size '2M'
          queue_limit_length '32'
          retry_max_interval '30'
          retry_forever true
        </buffer>
      </store>
    </match>

    <label @POSTGRES>
      <match **>
        @type stdout
      </match>
    </label>
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: a8s
    app.kubernetes.io/name: fluentd-aggregator
  name: a8s-fluentd-aggregator
  namespace: a8s-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: a8s
    app.kubernetes.io/name: fluentd-aggregator
  name: a8s-fluentd-aggregator
  namespace: a8s-system
spec:
  ports:
  - name: monitor
    port: 24220
    protocol: TCP
    targetPort: monitor
  - name: forward
    port: 24224
    protocol: TCP
    targetPort: forward
  selector:
    app.kubernetes.io/instance: a8s
    app.kubernetes.io/name: fluentd-aggregator
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: a8s
    app.kubernetes.io/name: fluentd-aggregator
    a8s.anynines/logging: "true"
  name: a8s-fluentd-aggregator
  namespace: a8s-system
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: a8s
      app.kubernetes.io/name: fluentd-aggregator
      a8s.anynines/logging: "true"
  serviceName: a8s-fluentd-aggregator
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: a8s
        app.kubernetes.io/name: fluentd-aggregator
        a8s.anynines/logging: "true"
    spec:
      containers:
      - image: "c4aeb71c-dd2a-4e6e-9385-1c3bb839307c.de.a9s.eu/a8s/fluentd:0.1.0"
        imagePullPolicy: IfNotPresent
        name: fluentd-aggregator
        ports:
        - containerPort: 9880
          name: http
          protocol: TCP
        - containerPort: 24220
          name: monitor
          protocol: TCP
        - containerPort: 24224
          name: forward
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluentd/etc
          name: config
        - mountPath: /fluentd/buffers
          name: buffer
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 511
          name: a8s-fluentd-aggregator
        name: config
      - emptyDir: {}
        name: buffer
