apiVersion: v1
data:
  fluent.conf: |-
    <source>
      type forward
      bind 0.0.0.0
      port 24224
    </source>

    <match **>
       @type elasticsearch
       @id out_es
       @log_level info
       include_tag_key true
       host elasticsearch.a8s-system.svc.cluster.local
       port 9200
       scheme 'http'
       ssl_verify 'true'
       ssl_version 'TLSv1_2'
       user 'elastic'
       password 'changeme'
       reload_connections 'false'
       reconnect_on_error 'true'
       reload_on_failure 'true'
       log_es_400_reason 'false'
       logstash_prefix 'logstash'
       logstash_dateformat '%Y.%m.%d'
       logstash_format 'true'
       index_name 'logstash'
       target_index_key use_nil
       type_name 'fluentd'
       include_timestamp 'false'
       request_timeout '5s'
       application_name use_default
       suppress_type_name 'true'
       enable_ilm 'false'
       ilm_policy_id use_default
       ilm_policy use_default
       ilm_policy_overwrite 'false'
       <buffer>
         flush_thread_count '8'
         flush_interval '5s'
         chunk_limit_size '2M'
         queue_limit_length '32'
         retry_max_interval '30'
         retry_forever true
       </buffer>
    </match>
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: a8s
    app.kubernetes.io/name: fluentd-aggregator
  name: a8s-fluentd-aggregator
  namespace: a8s-system
