apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: a8s
    app.kubernetes.io/name: fluentd-aggregator
  name: a8s-fluentd-aggregator
  namespace: a8s-system
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: a8s
      app.kubernetes.io/name: fluentd-aggregator
  serviceName: a8s-fluentd-aggregator
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: a8s
        app.kubernetes.io/name: fluentd-aggregator
    spec:
      containers:
      - image: ghcr.io/stevehipwell/fluentd-aggregator:1.12.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /fluent.healthcheck?json=%7B%22ping%22%3A+%22pong%22%7D
            port: http
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: fluentd-aggregator
        ports:
        - containerPort: 9880
          name: http
          protocol: TCP
        - containerPort: 24220
          name: monitor
          protocol: TCP
        - containerPort: 24224
          name: forward
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluentd/etc
          name: config
        - mountPath: /fluentd/buffers
          name: buffer
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 511
          name: a8s-fluentd-aggregator
        name: config
      - emptyDir: {}
        name: buffer
