apiVersion: v1
kind: Namespace
metadata:
  name: a8s-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: a8s-catalog
  namespace: a8s-system
spec:
  sourceType: grpc
  image: public.ecr.aws/w5n9a2g2/a9s-ds-for-k8s/dev/a8s-olm-catalog
  displayName: a8s DataService Catalog
  publisher: anynines
  updateStrategy:
    registryPoll:
      interval: 10m
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: a8s-operators
  namespace: a8s-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: a8s-postgresql
  namespace: a8s-system
spec:
  channel: stable
  name: postgresql-operator
  sourceNamespace: a8s-system
  source: a8s-catalog
