{{- $namespace := include "a8s-backup-manager.namespace" . -}}
{{- $saName := default "a8s-backup-manager-account" .Values.serviceAccount.name -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-leader-election-role
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: a8s-backup-manager
    app.kubernetes.io/part-of: a8s-backup
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-leader-election-rolebinding
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: a8s-backup-manager
    app.kubernetes.io/part-of: a8s-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backup-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ $namespace }}
