{{- if .Values.backupStorageConfig.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backupStorageConfig.secret.name }}
  namespace: {{ include "a8s-backup-manager.namespace" . }}
  labels:
    {{- include "a8s-backup-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.backupStorageConfig.secret.accessKeyId }}
  access-key-id: {{ .Values.backupStorageConfig.secret.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.backupStorageConfig.secret.secretAccessKey }}
  secret-access-key: {{ .Values.backupStorageConfig.secret.secretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.backupStorageConfig.secret.encryptionPassword }}
  encryption-password: {{ .Values.backupStorageConfig.secret.encryptionPassword | b64enc | quote }}
  {{- end }}
{{- end }}
