apiVersion: v1
data:
  kibana.yml: ZWxhc3RpY3NlYXJjaC5ob3N0czoKLSBodHRwOi8vYThzLW9wZW5kaXN0cm8tZXMtY2xpZW50LXNlcnZpY2UuYThzLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbDo5MjAwCnNlcnZlci5ob3N0OiAwLjAuMC4wCnNlcnZlci5uYW1lOiBraWJhbmE=
kind: Secret
metadata:
  labels:
    release: a8s
  name: a8s-opendistro-es-kibana-config
  namespace: a8s-system
type: Opaque
