apiVersion: v1
kind: Service
metadata:
  labels:
    app: a8s-opendistro-es
    release: a8s
    role: data
  name: a8s-opendistro-es-data-svc
  namespace: a8s-system
spec:
  ports:
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: metrics
    port: 9600
    protocol: TCP
    targetPort: 9600
  - name: rca
    port: 9650
    protocol: TCP
    targetPort: 9650
  selector:
    role: data
  sessionAffinity: None
  type: ClusterIP
