apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: a8s-opendistro-es
    release: a8s
    role: master
  name: a8s-opendistro-es-master
  namespace: a8s-system
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: a8s-opendistro-es
      release: a8s
      role: master
  serviceName: a8s-opendistro-es-discovery
  template:
    metadata:
      labels:
        app: a8s-opendistro-es
        release: a8s
        role: master
    spec:
      containers:
      - env:
        - name: cluster.name
          value: elasticsearch
        - name: cluster.initial_master_nodes
          value: a8s-opendistro-es-master-0,
        - name: node.master
          value: "true"
        - name: node.ingest
          value: "false"
        - name: node.data
          value: "false"
        - name: network.host
          value: 0.0.0.0
        - name: node.name
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: a8s-opendistro-es-discovery
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        image: docker.io/amazon/opendistro-for-elasticsearch:1.13.2
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: transport
          timeoutSeconds: 1
        name: elasticsearch
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9600
          name: metrics
          protocol: TCP
        - containerPort: 9650
          name: rca
          protocol: TCP
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_CHROOT
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
        - mountPath: /usr/share/elasticsearch/config/logging.yml
          name: config
          subPath: logging.yml
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: docker.io/busybox:1.27.2
        imagePullPolicy: IfNotPresent
        name: init-sysctl
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        image: docker.io/busybox:1.27.2
        imagePullPolicy: IfNotPresent
        name: fixmount
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: a8s-opendistro-es-es
      serviceAccountName: a8s-opendistro-es-es
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        secret:
          defaultMode: 420
          secretName: a8s-opendistro-es-es-config
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      volumeMode: Filesystem
