apiVersion: v1
kind: Service
metadata:
  labels:
    release: a8s
    role: kibana
  name: a8s-opendistro-es-kibana-svc
  namespace: a8s-system
spec:
  ports:
  - name: kibana-svc
    port: 443
    protocol: TCP
    targetPort: 5601
  selector:
    role: kibana
  sessionAffinity: None
  type: ClusterIP
