apiVersion: postgresql.anynines.com/v1alpha1
kind: Postgresql
metadata:
  name: sample-pg-cluster
spec:
  replicas: 3
  image: "registry.opensource.zalan.do/acid/spilo-13:2.0-p2"
  backupAgentImage: "public.ecr.aws/w5n9a2g2/a9s-ds-for-k8s/dev/backup-agent:ca8b816c0b600f7e4b99c9612fe34cbe60fe452e"
  resources:
    requests:
      cpu: 100m
    limits:
      memory: 100Mi
