apiVersion: postgresql.anynines.com/v1alpha1
kind: Postgresql
metadata:
  name: sample-pg-cluster
spec:
  replicas: 3
  volumeSizeGiB: 1
  version: 14
  resources:
    requests:
      cpu: 100m
    limits:
      memory: 100Mi
