apiVersion: postgresql.anynines.com/v1alpha1
kind: Postgresql
metadata:
  name: sample-pg-cluster
spec:
  replicas: 3
  volumeSize: 1Gi
  version: 14
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 500Mi
