{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "service-binding-manager-account" .Values.serviceAccount.name }}
  namespace: {{ include "a8s-service-binding-controller.namespace" . }}
  labels:
    {{- include "a8s-service-binding-controller.labels" . | nindent 4 }}
{{- end }}
