apiVersion: v1
kind: Service
metadata:
  name: service-binding-controller-manager-metrics-service
  namespace: {{ include "a8s-service-binding-controller.namespace" . }}
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/created-by: a8s-service-binding-controller
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/name: service-binding-controller-manager
    app.kubernetes.io/part-of: a8s-service-binding
    control-plane: controller-manager
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  ports:
    - name: https
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: service-binding-controller-manager
    app.kubernetes.io/part-of: a8s-service-binding
    control-plane: controller-manager
